Excursion and Price entity
BaranekD/pa165-blue-bat pull request #17
Opened 2021-04-04 08:29 UTC by MrJumpl

2021-04-04 11:48 UTC, Madoran approved these changes

2021-04-04 23:52 UTC, BaranekD requested changes

2021-04-04 23:52 UTC, BaranekD commented on src/main/java/cz/muni/fi/pa165/bluebat/dao/ExcursionDao.java
> + */
U interfaců to asi bude chtít trošku obsáhlejší Javadoc - je to i v popisu milestonu.

2021-04-04 23:52 UTC, BaranekD commented on src/main/java/cz/muni/fi/pa165/bluebat/dao/ExcursionDaoImpl.java
> +        em.detach(excursion);
Zde by myslím mělo být remove místo detach.

2021-04-04 23:52 UTC, BaranekD commented on src/main/java/cz/muni/fi/pa165/bluebat/dao/PriceDao.java
> + */
Opět by to chtělo obsáhlejší javadoc.

2021-04-04 23:52 UTC, BaranekD commented on src/main/java/cz/muni/fi/pa165/bluebat/dao/PriceDaoImpl.java
> +        em.detach(price);
Opět remove místo detach

2021-04-04 23:52 UTC, BaranekD commented on src/main/java/cz/muni/fi/pa165/bluebat/entity/Excursion.java
> +    }
Zde by šel pro generování getterů a setterů použít Lombok. Všechen tento kód by se pak mohl odstranit. Anotace Getter (případně Setter) umístěná nad classou jej vygeneruje pro všechny atributy. Pokud se anotace umístí nad atribut, pak je kod vygenerován pouze pro daný atribut. Protože to však ve výsledku generuje stejný kod jako IDE, pokud chceme tyto metody nějak modifikovat (což zde platí pro getPrices), Lombok nelze pro daný atribut použít. Jde s nim vygenerovat i toString, equals a hashCode, nicméně pro equals a hashCode zde opět nelze použít, protože je potřeba tyto metody mírně upravit oproti tomu, jak je IDE vygeneruje.

2021-04-04 23:52 UTC, BaranekD commented on src/main/java/cz/muni/fi/pa165/bluebat/entity/Excursion.java
> +import javax.persistence.*;
Většina programátorů je proti používání wildcard importů (možnost konfliktů, menší přehled v tom co za metody se vlastně používá, ...)

2021-04-04 23:52 UTC, BaranekD commented on src/main/java/cz/muni/fi/pa165/bluebat/entity/Price.java
>  public class Price {
Opět by zde šel použít Lombok

2021-04-04 23:52 UTC, BaranekD commented on src/main/java/cz/muni/fi/pa165/bluebat/entity/Excursion.java
> +        if (getDescription() != null ? getDescription().equals(excursion.getDescription()) : excursion.getDescription() != null)
Zde přemýšlím, jestli je třeba používat description. Pro dvě exkurze se stejným jménem a datem, navíc na stejné místo, by už možná mohlo platit, že jsou stejné. Ale tohle je spíš jen takový koment na zamyšlení.

2021-04-04 23:52 UTC, BaranekD commented on src/main/java/cz/muni/fi/pa165/bluebat/service/ExcursionService.java
> + */
Zde opět asi bude potřeba obsáhlejší javadoc

2021-04-04 23:52 UTC, BaranekD commented on src/main/java/cz/muni/fi/pa165/bluebat/service/PriceService.java
> + */
Zase javadoc

2021-04-05 09:04 UTC, BaranekD approved these changes

2021-04-05 09:05 UTC, merged