Implemented entity Reservation with DAO and service layer
BaranekD/pa165-blue-bat pull request #18
Opened 2021-04-04 20:59 UTC by BaranekD

2021-04-05 09:21 UTC, MrJumpl approved these changes

2021-04-05 09:21 UTC, MrJumpl commented on src/main/java/cz/muni/fi/pa165/bluebat/service/ReservationService.java
> +    void updateReservation(Reservation r);
Přijde mi to trochu nejednotné, když máš create/delete a najednou máš updateReservation

2021-04-05 09:21 UTC, MrJumpl commented on src/main/java/cz/muni/fi/pa165/bluebat/entity/Reservation.java
> +        return customer.equals(reservation.getCustomer()) && trip.equals(reservation.getTrip());
Nechybí tady null checky? Je pravda, že jak to máš napsané, tak pokud ten obejkt dostaneš z DB, tak null nebudou, ale nově vytvořené objetky mohou obsahovat null.

2021-04-05 18:00 UTC, Madoran requested changes

2021-04-05 18:00 UTC, Madoran commented on src/main/java/cz/muni/fi/pa165/bluebat/entity/Reservation.java
> +    @OneToOne()
```suggestion
    @OneToMany(mappedBy = "reservation")
```

2021-04-05 20:33 UTC, MrJumpl commented on src/main/java/cz/muni/fi/pa165/bluebat/dao/ReservationDao.java
> +public interface ReservationDao {
Ještě bych přidal funkci findAll(), která by vrátila všechny rezervace, To si myslím bude dobré, když admin bude chtít vidět všechny rezervace

2021-04-06 13:26 UTC, BaranekD commented on src/main/java/cz/muni/fi/pa165/bluebat/entity/Reservation.java
> +    @OneToOne()
Protože to tedy alespoň prozatím budeme držet OneToOne, tak to nechávám, jak to momentálně je.

2021-04-06 22:17 UTC, Madoran approved these changes

2021-04-06 22:18 UTC, merged