Create entity Trip
BaranekD/pa165-blue-bat pull request #19
Opened 2021-04-05 09:00 UTC by ondrejvaca

2021-04-05 09:44 UTC, MrJumpl requested changes

2021-04-05 09:44 UTC, MrJumpl commented on src/main/java/cz/muni/fi/pa165/bluebat/entity/Trip.java
> +    private Price price;
Cena byla spíš zamýšlená, aby mohla fungovat i jako historie, proto by tady měl spíš být list cen a spojeno přes JoinTable

2021-04-05 09:44 UTC, MrJumpl commented on src/main/java/cz/muni/fi/pa165/bluebat/entity/Trip.java
> +        return dateFrom.equals(trip.getDateFrom())&&dateTo.equals(trip.getDateFrom())&&destination.equals(trip.getDestination());
Spíš na zamyšlení, jestli by tady neměly být null checky.  Sice u objektu z DB to nully nebudou, ale nově vytvořený objetk může obsahovat nully.

2021-04-05 11:12 UTC, BaranekD requested changes

2021-04-05 11:12 UTC, BaranekD commented on src/main/java/cz/muni/fi/pa165/bluebat/dao/TripDao.java
> +    void remove(Trip trip);
Tady navrhuji jen kosmetickou úpravu přejmenovat remove na delete, ať to máme sjednocené mezi entitami

2021-04-05 11:12 UTC, BaranekD commented on src/main/java/cz/muni/fi/pa165/bluebat/dao/TripDaoImpl.java
> +    public void remove(Trip trip) {
Opět by mohlo být přejmenováno na delete

2021-04-05 11:12 UTC, BaranekD commented on src/main/java/cz/muni/fi/pa165/bluebat/entity/Trip.java
> +import javax.persistence.*;
Vyvaruj se prosím wildcard importů

2021-04-05 11:12 UTC, BaranekD commented on src/main/java/cz/muni/fi/pa165/bluebat/service/TripService.java
> +    void remove(Trip trip);
Mohlo by být přejmenováno na delete

2021-04-05 11:12 UTC, BaranekD commented on src/main/java/cz/muni/fi/pa165/bluebat/service/TripServiceImpl.java
> +    public TripServiceImpl(TripDao tripDao) {
Chybí Autowired

2021-04-05 11:12 UTC, BaranekD commented on src/main/java/cz/muni/fi/pa165/bluebat/service/TripServiceImpl.java
> +    public void remove(Trip trip) {
Přejmenovat na delete

2021-04-05 11:12 UTC, BaranekD commented on src/main/java/cz/muni/fi/pa165/bluebat/service/TripServiceImpl.java
> +}
Prosím přidej prázdný řádek na konec filu

2021-04-05 20:32 UTC, MrJumpl commented on src/main/java/cz/muni/fi/pa165/bluebat/dao/TripDao.java
> +public interface TripDao {
Ještě bych přidal funkci findAll(), která by vrátila všechno, To si myslím bude dobré, když budeme chtít zobrazit všechny na jedné stránce pro zákazníky

2021-04-06 23:25 UTC, MrJumpl requested changes
Jedna malá drobnost, jinak za mě ok

2021-04-06 23:25 UTC, MrJumpl commented on src/main/java/cz/muni/fi/pa165/bluebat/entity/Trip.java
> +    private Price price;
Tady by měl být list Price, proto potřeba i upravit getter metodu (bude stejná jako u exkurzí, nezapomeň odebrat anotaci @Getter)
```suggestion
    private List<Price> price;
```

2021-04-06 23:49 UTC, MrJumpl commented on src/main/java/cz/muni/fi/pa165/bluebat/entity/Trip.java
> +    private Set<Price> price;
Promiň, ale špatně jsem se vyjádřil. Podle mého názoru by bylo lepší, kdyby to byl list a ne set, protože nám právě jde o to pořadí, které získáme z DB díky OrderBy. Set sám o sobě nezaručuje pořadí si myslím 🤔

2021-04-07 00:05 UTC, MrJumpl approved these changes
Promiň, že jsem tě zdržel 🙂

2021-04-07 00:19 UTC, Madoran approved these changes

2021-04-07 07:00 UTC, merged