M2 repair-Customer
BaranekD/pa165-blue-bat pull request #71
Opened 2021-05-17 21:57 UTC by ondrejvaca

2021-05-18 13:19 UTC, Madoran approved these changes

2021-05-18 14:37 UTC, MrJumpl requested changes

2021-05-18 14:37 UTC, MrJumpl commented on travel-agency-service/src/main/java/cz/muni/fi/pa165/bluebat/service/CustomerServiceImpl.java
> +
Zbytečně při volání mazání uživatele přistupuješ dvakrát do DB (poprvé ve facade a podruhé tady na řádku 34). Celý tento blok mi přijde zbytečný. Pokud je totiž null, tak to projde a nic se nestane, pokud už v DB není, tak se taky nic nestane.

2021-05-18 14:37 UTC, MrJumpl commented on travel-agency-service/src/test/java/cz/muni/fi/pa165/bluebat/facade/CustomerFacadeImplTest.java
> +    public void getExcursionById_nullId_IllegalArgumentException() {
přejmenovat test, protože voláš getCustomerById a ne getExcursionById
```suggestion
    public void getCustomerById_nullId_IllegalArgumentException() {
```

2021-05-18 14:37 UTC, MrJumpl commented on travel-agency-service/src/test/java/cz/muni/fi/pa165/bluebat/facade/CustomerFacadeImplTest.java
> +    public void getExcursionById_negative_IllegalArgumentException() {
přejmenovat test, protože voláš getCustomerById a ne getExcursionById
```suggestion
    public void getCustomerById_negative_IllegalArgumentException() {
```

2021-05-19 10:01 UTC, MrJumpl approved these changes

2021-05-20 22:50 UTC, merged